apiVersion: v1
kind: Service
metadata:
  name: ${APP_INSTANCE_NAME}-frontend-svc
  namespace: $NAMESPACE
  labels:
    app.kubernetes.io/name: "$APP_INSTANCE_NAME"
    app.kubernetes.io/component: pocketstudio-frontend
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: "$APP_INSTANCE_NAME"
    app.kubernetes.io/component: pocketstudio-frontend
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
