apiVersion: v1
kind: Secret
metadata:
  name: ${APP_INSTANCE_NAME}-secrets
  namespace: $NAMESPACE
  labels:
    app.kubernetes.io/name: "$APP_INSTANCE_NAME"
type: Opaque
stringData:
  # Only fal.ai key needed!
  # Google API key NOT needed (using Workload Identity)
    fal-key: "$CUSTOMER_FAL_KEY"
    gcp-bucket: "$CUSTOMER_GCP_BUCKET"
    gcp-project: "$CUSTOMER_GCP_PROJECT"

