apiVersion: v1
kind: ServiceAccount
metadata:
  name: $APP_INSTANCE_NAME-sa
  namespace: $NAMESPACE
  labels:
    app.kubernetes.io/name: "$APP_INSTANCE_NAME"
  annotations:
    # This annotation links the Kubernetes SA to GCP SA
    # Format: <gcp-sa-name>@<project-id>.iam.gserviceaccount.com
    iam.gke.io/gcp-service-account: "pocketstudio@PROJECT_ID.iam.gserviceaccount.com"
